name: 'On-Demand: Start Staging'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  spin-up-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: |
          echo "This action is running from: ${{ github.repository }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::064566626562:role/github-actions-app-repo-role
          aws-region: eu-north-1

      - name: Invoke Start Lambda
        run: |
          echo "Starting 2-hour lease via Step Function..."
          aws stepfunctions start-execution \
            --state-machine-arn "arn:aws:states:eu-north-1:064566626562:stateMachine:staging-app-lease"

          echo "Lease started. Server will auto-stop in 2 hours."